// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boomerangz/control/v1/control.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusSnapshot        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatusResponse) GetStatus() *StatusSnapshot {
	if x != nil {
		return x.Status
	}
	return nil
}

type WatchStatusRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IntervalMilliseconds uint32                 `protobuf:"varint,1,opt,name=interval_milliseconds,json=intervalMilliseconds,proto3" json:"interval_milliseconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WatchStatusRequest) Reset() {
	*x = WatchStatusRequest{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStatusRequest) ProtoMessage() {}

func (x *WatchStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStatusRequest.ProtoReflect.Descriptor instead.
func (*WatchStatusRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *WatchStatusRequest) GetIntervalMilliseconds() uint32 {
	if x != nil {
		return x.IntervalMilliseconds
	}
	return 0
}

type WatchStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *StatusSnapshot        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchStatusResponse) Reset() {
	*x = WatchStatusResponse{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchStatusResponse) ProtoMessage() {}

func (x *WatchStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchStatusResponse.ProtoReflect.Descriptor instead.
func (*WatchStatusResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *WatchStatusResponse) GetStatus() *StatusSnapshot {
	if x != nil {
		return x.Status
	}
	return nil
}

type QueueStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Capacity      uint32                 `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Pending       uint32                 `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	JobIds        []string               `protobuf:"bytes,4,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatus) Reset() {
	*x = QueueStatus{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatus) ProtoMessage() {}

func (x *QueueStatus) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatus.ProtoReflect.Descriptor instead.
func (*QueueStatus) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *QueueStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueStatus) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *QueueStatus) GetPending() uint32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *QueueStatus) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

type JobStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pool            string                 `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Job             string                 `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	Dataset         string                 `protobuf:"bytes,3,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Target          string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	State           string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Reason          string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	ChangedUnixNano int64                  `protobuf:"varint,7,opt,name=changed_unix_nano,json=changedUnixNano,proto3" json:"changed_unix_nano,omitempty"`
	Pending         uint32                 `protobuf:"varint,8,opt,name=pending,proto3" json:"pending,omitempty"`
	QueuePosition   uint32                 `protobuf:"varint,9,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	Bytes           uint64                 `protobuf:"varint,10,opt,name=bytes,proto3" json:"bytes,omitempty"`
	TotalBytes      uint64                 `protobuf:"varint,11,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	BytesPerSecond  float64                `protobuf:"fixed64,12,opt,name=bytes_per_second,json=bytesPerSecond,proto3" json:"bytes_per_second,omitempty"`
	EtaNanoseconds  int64                  `protobuf:"varint,13,opt,name=eta_nanoseconds,json=etaNanoseconds,proto3" json:"eta_nanoseconds,omitempty"`
	TotalKnown      bool                   `protobuf:"varint,14,opt,name=total_known,json=totalKnown,proto3" json:"total_known,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *JobStatus) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *JobStatus) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *JobStatus) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *JobStatus) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *JobStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *JobStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *JobStatus) GetChangedUnixNano() int64 {
	if x != nil {
		return x.ChangedUnixNano
	}
	return 0
}

func (x *JobStatus) GetPending() uint32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *JobStatus) GetQueuePosition() uint32 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

func (x *JobStatus) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *JobStatus) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *JobStatus) GetBytesPerSecond() float64 {
	if x != nil {
		return x.BytesPerSecond
	}
	return 0
}

func (x *JobStatus) GetEtaNanoseconds() int64 {
	if x != nil {
		return x.EtaNanoseconds
	}
	return 0
}

func (x *JobStatus) GetTotalKnown() bool {
	if x != nil {
		return x.TotalKnown
	}
	return false
}

type DatasetStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool                   `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Recursive            bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	NextSnapshotUnixNano int64                  `protobuf:"varint,4,opt,name=next_snapshot_unix_nano,json=nextSnapshotUnixNano,proto3" json:"next_snapshot_unix_nano,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DatasetStatus) Reset() {
	*x = DatasetStatus{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetStatus) ProtoMessage() {}

func (x *DatasetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetStatus.ProtoReflect.Descriptor instead.
func (*DatasetStatus) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *DatasetStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatasetStatus) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *DatasetStatus) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *DatasetStatus) GetNextSnapshotUnixNano() int64 {
	if x != nil {
		return x.NextSnapshotUnixNano
	}
	return 0
}

type StatusSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Revision         uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	ObservedUnixNano int64                  `protobuf:"varint,2,opt,name=observed_unix_nano,json=observedUnixNano,proto3" json:"observed_unix_nano,omitempty"`
	Generation       uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Datasets         []*DatasetStatus       `protobuf:"bytes,4,rep,name=datasets,proto3" json:"datasets,omitempty"`
	Queues           []*QueueStatus         `protobuf:"bytes,5,rep,name=queues,proto3" json:"queues,omitempty"`
	Jobs             []*JobStatus           `protobuf:"bytes,6,rep,name=jobs,proto3" json:"jobs,omitempty"`
	ConfigGeneration uint64                 `protobuf:"varint,7,opt,name=config_generation,json=configGeneration,proto3" json:"config_generation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusSnapshot) Reset() {
	*x = StatusSnapshot{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusSnapshot) ProtoMessage() {}

func (x *StatusSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusSnapshot.ProtoReflect.Descriptor instead.
func (*StatusSnapshot) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *StatusSnapshot) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *StatusSnapshot) GetObservedUnixNano() int64 {
	if x != nil {
		return x.ObservedUnixNano
	}
	return 0
}

func (x *StatusSnapshot) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *StatusSnapshot) GetDatasets() []*DatasetStatus {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *StatusSnapshot) GetQueues() []*QueueStatus {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *StatusSnapshot) GetJobs() []*JobStatus {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *StatusSnapshot) GetConfigGeneration() uint64 {
	if x != nil {
		return x.ConfigGeneration
	}
	return 0
}

type ListDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsRequest) Reset() {
	*x = ListDatasetsRequest{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsRequest) ProtoMessage() {}

func (x *ListDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{8}
}

type ListDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Datasets      []*DatasetStatus       `protobuf:"bytes,2,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsResponse) Reset() {
	*x = ListDatasetsResponse{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsResponse) ProtoMessage() {}

func (x *ListDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{9}
}

func (x *ListDatasetsResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ListDatasetsResponse) GetDatasets() []*DatasetStatus {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type TriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []string               `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{10}
}

func (x *TriggerRequest) GetDatasets() []string {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type ReconcileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{11}
}

type TriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      []string               `protobuf:"bytes,1,rep,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{12}
}

func (x *TriggerResponse) GetAccepted() []string {
	if x != nil {
		return x.Accepted
	}
	return nil
}

type ReconcileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{13}
}

func (x *ReconcileResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ReloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRequest) Reset() {
	*x = ReloadRequest{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRequest) ProtoMessage() {}

func (x *ReloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRequest.ProtoReflect.Descriptor instead.
func (*ReloadRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{14}
}

type ReloadResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Generation      uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Applied         []string               `protobuf:"bytes,2,rep,name=applied,proto3" json:"applied,omitempty"`
	RestartRequired []string               `protobuf:"bytes,3,rep,name=restart_required,json=restartRequired,proto3" json:"restart_required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReloadResponse) Reset() {
	*x = ReloadResponse{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadResponse) ProtoMessage() {}

func (x *ReloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadResponse.ProtoReflect.Descriptor instead.
func (*ReloadResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{15}
}

func (x *ReloadResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ReloadResponse) GetApplied() []string {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *ReloadResponse) GetRestartRequired() []string {
	if x != nil {
		return x.RestartRequired
	}
	return nil
}

type CleanRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Datasets              []string               `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	Recursive             bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	All                   bool                   `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	DestroyOwnedSnapshots bool                   `protobuf:"varint,4,opt,name=destroy_owned_snapshots,json=destroyOwnedSnapshots,proto3" json:"destroy_owned_snapshots,omitempty"`
	Apply                 bool                   `protobuf:"varint,5,opt,name=apply,proto3" json:"apply,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CleanRequest) Reset() {
	*x = CleanRequest{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanRequest) ProtoMessage() {}

func (x *CleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanRequest.ProtoReflect.Descriptor instead.
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{16}
}

func (x *CleanRequest) GetDatasets() []string {
	if x != nil {
		return x.Datasets
	}
	return nil
}

func (x *CleanRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *CleanRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

func (x *CleanRequest) GetDestroyOwnedSnapshots() bool {
	if x != nil {
		return x.DestroyOwnedSnapshots
	}
	return false
}

func (x *CleanRequest) GetApply() bool {
	if x != nil {
		return x.Apply
	}
	return false
}

type CleanAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Property      string                 `protobuf:"bytes,3,opt,name=property,proto3" json:"property,omitempty"`
	Guid          uint64                 `protobuf:"varint,4,opt,name=guid,proto3" json:"guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanAction) Reset() {
	*x = CleanAction{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanAction) ProtoMessage() {}

func (x *CleanAction) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanAction.ProtoReflect.Descriptor instead.
func (*CleanAction) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{17}
}

func (x *CleanAction) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CleanAction) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *CleanAction) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *CleanAction) GetGuid() uint64 {
	if x != nil {
		return x.Guid
	}
	return 0
}

type CleanPlan struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Dataset               string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Recursive             bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	DestroyOwnedSnapshots bool                   `protobuf:"varint,3,opt,name=destroy_owned_snapshots,json=destroyOwnedSnapshots,proto3" json:"destroy_owned_snapshots,omitempty"`
	Actions               []*CleanAction         `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	Blockers              []string               `protobuf:"bytes,5,rep,name=blockers,proto3" json:"blockers,omitempty"`
	Warnings              []string               `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Applied               uint32                 `protobuf:"varint,7,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CleanPlan) Reset() {
	*x = CleanPlan{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanPlan) ProtoMessage() {}

func (x *CleanPlan) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanPlan.ProtoReflect.Descriptor instead.
func (*CleanPlan) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{18}
}

func (x *CleanPlan) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *CleanPlan) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *CleanPlan) GetDestroyOwnedSnapshots() bool {
	if x != nil {
		return x.DestroyOwnedSnapshots
	}
	return false
}

func (x *CleanPlan) GetActions() []*CleanAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *CleanPlan) GetBlockers() []string {
	if x != nil {
		return x.Blockers
	}
	return nil
}

func (x *CleanPlan) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *CleanPlan) GetApplied() uint32 {
	if x != nil {
		return x.Applied
	}
	return 0
}

type CleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*CleanPlan           `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanResponse) Reset() {
	*x = CleanResponse{}
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanResponse) ProtoMessage() {}

func (x *CleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_control_v1_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanResponse.ProtoReflect.Descriptor instead.
func (*CleanResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_control_v1_control_proto_rawDescGZIP(), []int{19}
}

func (x *CleanResponse) GetPlans() []*CleanPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *CleanResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_boomerangz_control_v1_control_proto protoreflect.FileDescriptor

const file_boomerangz_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"#boomerangz/control/v1/control.proto\x12\x15boomerangz.control.v1\"\x12\n" +
	"\x10GetStatusRequest\"R\n" +
	"\x11GetStatusResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\v2%.boomerangz.control.v1.StatusSnapshotR\x06status\"I\n" +
	"\x12WatchStatusRequest\x123\n" +
	"\x15interval_milliseconds\x18\x01 \x01(\rR\x14intervalMilliseconds\"T\n" +
	"\x13WatchStatusResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\v2%.boomerangz.control.v1.StatusSnapshotR\x06status\"p\n" +
	"\vQueueStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\rR\bcapacity\x12\x18\n" +
	"\apending\x18\x03 \x01(\rR\apending\x12\x17\n" +
	"\ajob_ids\x18\x04 \x03(\tR\x06jobIds\"\xa9\x03\n" +
	"\tJobStatus\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\x12\x10\n" +
	"\x03job\x18\x02 \x01(\tR\x03job\x12\x18\n" +
	"\adataset\x18\x03 \x01(\tR\adataset\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12*\n" +
	"\x11changed_unix_nano\x18\a \x01(\x03R\x0fchangedUnixNano\x12\x18\n" +
	"\apending\x18\b \x01(\rR\apending\x12%\n" +
	"\x0equeue_position\x18\t \x01(\rR\rqueuePosition\x12\x14\n" +
	"\x05bytes\x18\n" +
	" \x01(\x04R\x05bytes\x12\x1f\n" +
	"\vtotal_bytes\x18\v \x01(\x04R\n" +
	"totalBytes\x12(\n" +
	"\x10bytes_per_second\x18\f \x01(\x01R\x0ebytesPerSecond\x12'\n" +
	"\x0feta_nanoseconds\x18\r \x01(\x03R\x0eetaNanoseconds\x12\x1f\n" +
	"\vtotal_known\x18\x0e \x01(\bR\n" +
	"totalKnown\"\x90\x01\n" +
	"\rDatasetStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x02 \x01(\bR\x06active\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\x125\n" +
	"\x17next_snapshot_unix_nano\x18\x04 \x01(\x03R\x14nextSnapshotUnixNano\"\xdb\x02\n" +
	"\x0eStatusSnapshot\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12,\n" +
	"\x12observed_unix_nano\x18\x02 \x01(\x03R\x10observedUnixNano\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x12@\n" +
	"\bdatasets\x18\x04 \x03(\v2$.boomerangz.control.v1.DatasetStatusR\bdatasets\x12:\n" +
	"\x06queues\x18\x05 \x03(\v2\".boomerangz.control.v1.QueueStatusR\x06queues\x124\n" +
	"\x04jobs\x18\x06 \x03(\v2 .boomerangz.control.v1.JobStatusR\x04jobs\x12+\n" +
	"\x11config_generation\x18\a \x01(\x04R\x10configGeneration\"\x15\n" +
	"\x13ListDatasetsRequest\"x\n" +
	"\x14ListDatasetsResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12@\n" +
	"\bdatasets\x18\x02 \x03(\v2$.boomerangz.control.v1.DatasetStatusR\bdatasets\",\n" +
	"\x0eTriggerRequest\x12\x1a\n" +
	"\bdatasets\x18\x01 \x03(\tR\bdatasets\"\x12\n" +
	"\x10ReconcileRequest\"-\n" +
	"\x0fTriggerResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x03(\tR\baccepted\"/\n" +
	"\x11ReconcileResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x0f\n" +
	"\rReloadRequest\"u\n" +
	"\x0eReloadResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x18\n" +
	"\aapplied\x18\x02 \x03(\tR\aapplied\x12)\n" +
	"\x10restart_required\x18\x03 \x03(\tR\x0frestartRequired\"\xa8\x01\n" +
	"\fCleanRequest\x12\x1a\n" +
	"\bdatasets\x18\x01 \x03(\tR\bdatasets\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\x126\n" +
	"\x17destroy_owned_snapshots\x18\x04 \x01(\bR\x15destroyOwnedSnapshots\x12\x14\n" +
	"\x05apply\x18\x05 \x01(\bR\x05apply\"s\n" +
	"\vCleanAction\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x1a\n" +
	"\bproperty\x18\x03 \x01(\tR\bproperty\x12\x12\n" +
	"\x04guid\x18\x04 \x01(\x04R\x04guid\"\x8b\x02\n" +
	"\tCleanPlan\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\x126\n" +
	"\x17destroy_owned_snapshots\x18\x03 \x01(\bR\x15destroyOwnedSnapshots\x12<\n" +
	"\aactions\x18\x04 \x03(\v2\".boomerangz.control.v1.CleanActionR\aactions\x12\x1a\n" +
	"\bblockers\x18\x05 \x03(\tR\bblockers\x12\x1a\n" +
	"\bwarnings\x18\x06 \x03(\tR\bwarnings\x12\x18\n" +
	"\aapplied\x18\a \x01(\rR\aapplied\"]\n" +
	"\rCleanResponse\x126\n" +
	"\x05plans\x18\x01 \x03(\v2 .boomerangz.control.v1.CleanPlanR\x05plans\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xc0\x02\n" +
	"\rStatusService\x12^\n" +
	"\tGetStatus\x12'.boomerangz.control.v1.GetStatusRequest\x1a(.boomerangz.control.v1.GetStatusResponse\x12f\n" +
	"\vWatchStatus\x12).boomerangz.control.v1.WatchStatusRequest\x1a*.boomerangz.control.v1.WatchStatusResponse0\x01\x12g\n" +
	"\fListDatasets\x12*.boomerangz.control.v1.ListDatasetsRequest\x1a+.boomerangz.control.v1.ListDatasetsResponse2\xf5\x02\n" +
	"\x0eControlService\x12X\n" +
	"\aTrigger\x12%.boomerangz.control.v1.TriggerRequest\x1a&.boomerangz.control.v1.TriggerResponse\x12^\n" +
	"\tReconcile\x12'.boomerangz.control.v1.ReconcileRequest\x1a(.boomerangz.control.v1.ReconcileResponse\x12U\n" +
	"\x06Reload\x12$.boomerangz.control.v1.ReloadRequest\x1a%.boomerangz.control.v1.ReloadResponse\x12R\n" +
	"\x05Clean\x12#.boomerangz.control.v1.CleanRequest\x1a$.boomerangz.control.v1.CleanResponseB4Z2github.com/pdf/boomerangz/internal/control/rpc;rpcb\x06proto3"

var (
	file_boomerangz_control_v1_control_proto_rawDescOnce sync.Once
	file_boomerangz_control_v1_control_proto_rawDescData []byte
)

func file_boomerangz_control_v1_control_proto_rawDescGZIP() []byte {
	file_boomerangz_control_v1_control_proto_rawDescOnce.Do(func() {
		file_boomerangz_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boomerangz_control_v1_control_proto_rawDesc), len(file_boomerangz_control_v1_control_proto_rawDesc)))
	})
	return file_boomerangz_control_v1_control_proto_rawDescData
}

var file_boomerangz_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_boomerangz_control_v1_control_proto_goTypes = []any{
	(*GetStatusRequest)(nil),     // 0: boomerangz.control.v1.GetStatusRequest
	(*GetStatusResponse)(nil),    // 1: boomerangz.control.v1.GetStatusResponse
	(*WatchStatusRequest)(nil),   // 2: boomerangz.control.v1.WatchStatusRequest
	(*WatchStatusResponse)(nil),  // 3: boomerangz.control.v1.WatchStatusResponse
	(*QueueStatus)(nil),          // 4: boomerangz.control.v1.QueueStatus
	(*JobStatus)(nil),            // 5: boomerangz.control.v1.JobStatus
	(*DatasetStatus)(nil),        // 6: boomerangz.control.v1.DatasetStatus
	(*StatusSnapshot)(nil),       // 7: boomerangz.control.v1.StatusSnapshot
	(*ListDatasetsRequest)(nil),  // 8: boomerangz.control.v1.ListDatasetsRequest
	(*ListDatasetsResponse)(nil), // 9: boomerangz.control.v1.ListDatasetsResponse
	(*TriggerRequest)(nil),       // 10: boomerangz.control.v1.TriggerRequest
	(*ReconcileRequest)(nil),     // 11: boomerangz.control.v1.ReconcileRequest
	(*TriggerResponse)(nil),      // 12: boomerangz.control.v1.TriggerResponse
	(*ReconcileResponse)(nil),    // 13: boomerangz.control.v1.ReconcileResponse
	(*ReloadRequest)(nil),        // 14: boomerangz.control.v1.ReloadRequest
	(*ReloadResponse)(nil),       // 15: boomerangz.control.v1.ReloadResponse
	(*CleanRequest)(nil),         // 16: boomerangz.control.v1.CleanRequest
	(*CleanAction)(nil),          // 17: boomerangz.control.v1.CleanAction
	(*CleanPlan)(nil),            // 18: boomerangz.control.v1.CleanPlan
	(*CleanResponse)(nil),        // 19: boomerangz.control.v1.CleanResponse
}
var file_boomerangz_control_v1_control_proto_depIdxs = []int32{
	7,  // 0: boomerangz.control.v1.GetStatusResponse.status:type_name -> boomerangz.control.v1.StatusSnapshot
	7,  // 1: boomerangz.control.v1.WatchStatusResponse.status:type_name -> boomerangz.control.v1.StatusSnapshot
	6,  // 2: boomerangz.control.v1.StatusSnapshot.datasets:type_name -> boomerangz.control.v1.DatasetStatus
	4,  // 3: boomerangz.control.v1.StatusSnapshot.queues:type_name -> boomerangz.control.v1.QueueStatus
	5,  // 4: boomerangz.control.v1.StatusSnapshot.jobs:type_name -> boomerangz.control.v1.JobStatus
	6,  // 5: boomerangz.control.v1.ListDatasetsResponse.datasets:type_name -> boomerangz.control.v1.DatasetStatus
	17, // 6: boomerangz.control.v1.CleanPlan.actions:type_name -> boomerangz.control.v1.CleanAction
	18, // 7: boomerangz.control.v1.CleanResponse.plans:type_name -> boomerangz.control.v1.CleanPlan
	0,  // 8: boomerangz.control.v1.StatusService.GetStatus:input_type -> boomerangz.control.v1.GetStatusRequest
	2,  // 9: boomerangz.control.v1.StatusService.WatchStatus:input_type -> boomerangz.control.v1.WatchStatusRequest
	8,  // 10: boomerangz.control.v1.StatusService.ListDatasets:input_type -> boomerangz.control.v1.ListDatasetsRequest
	10, // 11: boomerangz.control.v1.ControlService.Trigger:input_type -> boomerangz.control.v1.TriggerRequest
	11, // 12: boomerangz.control.v1.ControlService.Reconcile:input_type -> boomerangz.control.v1.ReconcileRequest
	14, // 13: boomerangz.control.v1.ControlService.Reload:input_type -> boomerangz.control.v1.ReloadRequest
	16, // 14: boomerangz.control.v1.ControlService.Clean:input_type -> boomerangz.control.v1.CleanRequest
	1,  // 15: boomerangz.control.v1.StatusService.GetStatus:output_type -> boomerangz.control.v1.GetStatusResponse
	3,  // 16: boomerangz.control.v1.StatusService.WatchStatus:output_type -> boomerangz.control.v1.WatchStatusResponse
	9,  // 17: boomerangz.control.v1.StatusService.ListDatasets:output_type -> boomerangz.control.v1.ListDatasetsResponse
	12, // 18: boomerangz.control.v1.ControlService.Trigger:output_type -> boomerangz.control.v1.TriggerResponse
	13, // 19: boomerangz.control.v1.ControlService.Reconcile:output_type -> boomerangz.control.v1.ReconcileResponse
	15, // 20: boomerangz.control.v1.ControlService.Reload:output_type -> boomerangz.control.v1.ReloadResponse
	19, // 21: boomerangz.control.v1.ControlService.Clean:output_type -> boomerangz.control.v1.CleanResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_boomerangz_control_v1_control_proto_init() }
func file_boomerangz_control_v1_control_proto_init() {
	if File_boomerangz_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boomerangz_control_v1_control_proto_rawDesc), len(file_boomerangz_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_boomerangz_control_v1_control_proto_goTypes,
		DependencyIndexes: file_boomerangz_control_v1_control_proto_depIdxs,
		MessageInfos:      file_boomerangz_control_v1_control_proto_msgTypes,
	}.Build()
	File_boomerangz_control_v1_control_proto = out.File
	file_boomerangz_control_v1_control_proto_goTypes = nil
	file_boomerangz_control_v1_control_proto_depIdxs = nil
}
