d /etc/boomerangz 0750 root boomerangz -
d /etc/boomerangz/config.d 0750 root boomerangz -
d /etc/boomerangz/credentials.d 0750 root boomerangz -
d /var/lib/boomerangz 0750 boomerangz boomerangz -
d /run/boomerangz 0750 boomerangz boomerangz -
z /etc/boomerangz/config.toml 0640 root boomerangz -
