// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: boomerangz/replication/v1/remote.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteService_Capabilities_FullMethodName           = "/boomerangz.replication.v1.RemoteService/Capabilities"
	RemoteService_ListDatasets_FullMethodName           = "/boomerangz.replication.v1.RemoteService/ListDatasets"
	RemoteService_InspectDatasetIdentity_FullMethodName = "/boomerangz.replication.v1.RemoteService/InspectDatasetIdentity"
	RemoteService_InspectState_FullMethodName           = "/boomerangz.replication.v1.RemoteService/InspectState"
	RemoteService_CheckPermissions_FullMethodName       = "/boomerangz.replication.v1.RemoteService/CheckPermissions"
	RemoteService_CreateReceiveParent_FullMethodName    = "/boomerangz.replication.v1.RemoteService/CreateReceiveParent"
	RemoteService_AbortReceive_FullMethodName           = "/boomerangz.replication.v1.RemoteService/AbortReceive"
	RemoteService_DestroyDataset_FullMethodName         = "/boomerangz.replication.v1.RemoteService/DestroyDataset"
	RemoteService_SetProperties_FullMethodName          = "/boomerangz.replication.v1.RemoteService/SetProperties"
	RemoteService_InheritProperty_FullMethodName        = "/boomerangz.replication.v1.RemoteService/InheritProperty"
	RemoteService_Receive_FullMethodName                = "/boomerangz.replication.v1.RemoteService/Receive"
)

// RemoteServiceClient is the client API for RemoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RemoteServiceClient interface {
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error)
	InspectDatasetIdentity(ctx context.Context, in *InspectDatasetIdentityRequest, opts ...grpc.CallOption) (*InspectDatasetIdentityResponse, error)
	InspectState(ctx context.Context, in *InspectStateRequest, opts ...grpc.CallOption) (*InspectStateResponse, error)
	CheckPermissions(ctx context.Context, in *CheckPermissionsRequest, opts ...grpc.CallOption) (*CheckPermissionsResponse, error)
	CreateReceiveParent(ctx context.Context, in *CreateReceiveParentRequest, opts ...grpc.CallOption) (*CreateReceiveParentResponse, error)
	AbortReceive(ctx context.Context, in *AbortReceiveRequest, opts ...grpc.CallOption) (*AbortReceiveResponse, error)
	DestroyDataset(ctx context.Context, in *DestroyDatasetRequest, opts ...grpc.CallOption) (*DestroyDatasetResponse, error)
	SetProperties(ctx context.Context, in *SetPropertiesRequest, opts ...grpc.CallOption) (*SetPropertiesResponse, error)
	InheritProperty(ctx context.Context, in *InheritPropertyRequest, opts ...grpc.CallOption) (*InheritPropertyResponse, error)
	Receive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReceiveRequest, ReceiveResponse], error)
}

type remoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteServiceClient(cc grpc.ClientConnInterface) RemoteServiceClient {
	return &remoteServiceClient{cc}
}

func (c *remoteServiceClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, RemoteService_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasetsResponse)
	err := c.cc.Invoke(ctx, RemoteService_ListDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) InspectDatasetIdentity(ctx context.Context, in *InspectDatasetIdentityRequest, opts ...grpc.CallOption) (*InspectDatasetIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectDatasetIdentityResponse)
	err := c.cc.Invoke(ctx, RemoteService_InspectDatasetIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) InspectState(ctx context.Context, in *InspectStateRequest, opts ...grpc.CallOption) (*InspectStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectStateResponse)
	err := c.cc.Invoke(ctx, RemoteService_InspectState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) CheckPermissions(ctx context.Context, in *CheckPermissionsRequest, opts ...grpc.CallOption) (*CheckPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionsResponse)
	err := c.cc.Invoke(ctx, RemoteService_CheckPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) CreateReceiveParent(ctx context.Context, in *CreateReceiveParentRequest, opts ...grpc.CallOption) (*CreateReceiveParentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReceiveParentResponse)
	err := c.cc.Invoke(ctx, RemoteService_CreateReceiveParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) AbortReceive(ctx context.Context, in *AbortReceiveRequest, opts ...grpc.CallOption) (*AbortReceiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortReceiveResponse)
	err := c.cc.Invoke(ctx, RemoteService_AbortReceive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) DestroyDataset(ctx context.Context, in *DestroyDatasetRequest, opts ...grpc.CallOption) (*DestroyDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyDatasetResponse)
	err := c.cc.Invoke(ctx, RemoteService_DestroyDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) SetProperties(ctx context.Context, in *SetPropertiesRequest, opts ...grpc.CallOption) (*SetPropertiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPropertiesResponse)
	err := c.cc.Invoke(ctx, RemoteService_SetProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) InheritProperty(ctx context.Context, in *InheritPropertyRequest, opts ...grpc.CallOption) (*InheritPropertyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InheritPropertyResponse)
	err := c.cc.Invoke(ctx, RemoteService_InheritProperty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteServiceClient) Receive(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReceiveRequest, ReceiveResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RemoteService_ServiceDesc.Streams[0], RemoteService_Receive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReceiveRequest, ReceiveResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteService_ReceiveClient = grpc.ClientStreamingClient[ReceiveRequest, ReceiveResponse]

// RemoteServiceServer is the server API for RemoteService service.
// All implementations must embed UnimplementedRemoteServiceServer
// for forward compatibility.
type RemoteServiceServer interface {
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error)
	InspectDatasetIdentity(context.Context, *InspectDatasetIdentityRequest) (*InspectDatasetIdentityResponse, error)
	InspectState(context.Context, *InspectStateRequest) (*InspectStateResponse, error)
	CheckPermissions(context.Context, *CheckPermissionsRequest) (*CheckPermissionsResponse, error)
	CreateReceiveParent(context.Context, *CreateReceiveParentRequest) (*CreateReceiveParentResponse, error)
	AbortReceive(context.Context, *AbortReceiveRequest) (*AbortReceiveResponse, error)
	DestroyDataset(context.Context, *DestroyDatasetRequest) (*DestroyDatasetResponse, error)
	SetProperties(context.Context, *SetPropertiesRequest) (*SetPropertiesResponse, error)
	InheritProperty(context.Context, *InheritPropertyRequest) (*InheritPropertyResponse, error)
	Receive(grpc.ClientStreamingServer[ReceiveRequest, ReceiveResponse]) error
	mustEmbedUnimplementedRemoteServiceServer()
}

// UnimplementedRemoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteServiceServer struct{}

func (UnimplementedRemoteServiceServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedRemoteServiceServer) ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDatasets not implemented")
}
func (UnimplementedRemoteServiceServer) InspectDatasetIdentity(context.Context, *InspectDatasetIdentityRequest) (*InspectDatasetIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectDatasetIdentity not implemented")
}
func (UnimplementedRemoteServiceServer) InspectState(context.Context, *InspectStateRequest) (*InspectStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InspectState not implemented")
}
func (UnimplementedRemoteServiceServer) CheckPermissions(context.Context, *CheckPermissionsRequest) (*CheckPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPermissions not implemented")
}
func (UnimplementedRemoteServiceServer) CreateReceiveParent(context.Context, *CreateReceiveParentRequest) (*CreateReceiveParentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReceiveParent not implemented")
}
func (UnimplementedRemoteServiceServer) AbortReceive(context.Context, *AbortReceiveRequest) (*AbortReceiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortReceive not implemented")
}
func (UnimplementedRemoteServiceServer) DestroyDataset(context.Context, *DestroyDatasetRequest) (*DestroyDatasetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyDataset not implemented")
}
func (UnimplementedRemoteServiceServer) SetProperties(context.Context, *SetPropertiesRequest) (*SetPropertiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProperties not implemented")
}
func (UnimplementedRemoteServiceServer) InheritProperty(context.Context, *InheritPropertyRequest) (*InheritPropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InheritProperty not implemented")
}
func (UnimplementedRemoteServiceServer) Receive(grpc.ClientStreamingServer[ReceiveRequest, ReceiveResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedRemoteServiceServer) mustEmbedUnimplementedRemoteServiceServer() {}
func (UnimplementedRemoteServiceServer) testEmbeddedByValue()                       {}

// UnsafeRemoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteServiceServer will
// result in compilation errors.
type UnsafeRemoteServiceServer interface {
	mustEmbedUnimplementedRemoteServiceServer()
}

func RegisterRemoteServiceServer(s grpc.ServiceRegistrar, srv RemoteServiceServer) {
	// If the following call pancis, it indicates UnimplementedRemoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteService_ServiceDesc, srv)
}

func _RemoteService_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_ListDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).ListDatasets(ctx, req.(*ListDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_InspectDatasetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectDatasetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).InspectDatasetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_InspectDatasetIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).InspectDatasetIdentity(ctx, req.(*InspectDatasetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_InspectState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).InspectState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_InspectState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).InspectState(ctx, req.(*InspectStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_CheckPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).CheckPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_CheckPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).CheckPermissions(ctx, req.(*CheckPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_CreateReceiveParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReceiveParentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).CreateReceiveParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_CreateReceiveParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).CreateReceiveParent(ctx, req.(*CreateReceiveParentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_AbortReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).AbortReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_AbortReceive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).AbortReceive(ctx, req.(*AbortReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_DestroyDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).DestroyDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_DestroyDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).DestroyDataset(ctx, req.(*DestroyDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_SetProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPropertiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).SetProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_SetProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).SetProperties(ctx, req.(*SetPropertiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_InheritProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InheritPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteServiceServer).InheritProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteService_InheritProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteServiceServer).InheritProperty(ctx, req.(*InheritPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteService_Receive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RemoteServiceServer).Receive(&grpc.GenericServerStream[ReceiveRequest, ReceiveResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RemoteService_ReceiveServer = grpc.ClientStreamingServer[ReceiveRequest, ReceiveResponse]

// RemoteService_ServiceDesc is the grpc.ServiceDesc for RemoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "boomerangz.replication.v1.RemoteService",
	HandlerType: (*RemoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capabilities",
			Handler:    _RemoteService_Capabilities_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _RemoteService_ListDatasets_Handler,
		},
		{
			MethodName: "InspectDatasetIdentity",
			Handler:    _RemoteService_InspectDatasetIdentity_Handler,
		},
		{
			MethodName: "InspectState",
			Handler:    _RemoteService_InspectState_Handler,
		},
		{
			MethodName: "CheckPermissions",
			Handler:    _RemoteService_CheckPermissions_Handler,
		},
		{
			MethodName: "CreateReceiveParent",
			Handler:    _RemoteService_CreateReceiveParent_Handler,
		},
		{
			MethodName: "AbortReceive",
			Handler:    _RemoteService_AbortReceive_Handler,
		},
		{
			MethodName: "DestroyDataset",
			Handler:    _RemoteService_DestroyDataset_Handler,
		},
		{
			MethodName: "SetProperties",
			Handler:    _RemoteService_SetProperties_Handler,
		},
		{
			MethodName: "InheritProperty",
			Handler:    _RemoteService_InheritProperty_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Receive",
			Handler:       _RemoteService_Receive_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "boomerangz/replication/v1/remote.proto",
}
