// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: boomerangz/replication/v1/remote.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Operations      []string               `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *CapabilitiesResponse) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ListDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsRequest) Reset() {
	*x = ListDatasetsRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsRequest) ProtoMessage() {}

func (x *ListDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{2}
}

type Dataset struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	EncryptionRoot string                 `protobuf:"bytes,3,opt,name=encryption_root,json=encryptionRoot,proto3" json:"encryption_root,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{3}
}

func (x *Dataset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dataset) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Dataset) GetEncryptionRoot() string {
	if x != nil {
		return x.EncryptionRoot
	}
	return ""
}

type ListDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []*Dataset             `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsResponse) Reset() {
	*x = ListDatasetsResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsResponse) ProtoMessage() {}

func (x *ListDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{4}
}

func (x *ListDatasetsResponse) GetDatasets() []*Dataset {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type InspectDatasetIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectDatasetIdentityRequest) Reset() {
	*x = InspectDatasetIdentityRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectDatasetIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectDatasetIdentityRequest) ProtoMessage() {}

func (x *InspectDatasetIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectDatasetIdentityRequest.ProtoReflect.Descriptor instead.
func (*InspectDatasetIdentityRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{5}
}

func (x *InspectDatasetIdentityRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

type InspectDatasetIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Guid          uint64                 `protobuf:"varint,3,opt,name=guid,proto3" json:"guid,omitempty"`
	Pool          string                 `protobuf:"bytes,4,opt,name=pool,proto3" json:"pool,omitempty"`
	PoolGuid      uint64                 `protobuf:"varint,5,opt,name=pool_guid,json=poolGuid,proto3" json:"pool_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectDatasetIdentityResponse) Reset() {
	*x = InspectDatasetIdentityResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectDatasetIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectDatasetIdentityResponse) ProtoMessage() {}

func (x *InspectDatasetIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectDatasetIdentityResponse.ProtoReflect.Descriptor instead.
func (*InspectDatasetIdentityResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{6}
}

func (x *InspectDatasetIdentityResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InspectDatasetIdentityResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InspectDatasetIdentityResponse) GetGuid() uint64 {
	if x != nil {
		return x.Guid
	}
	return 0
}

func (x *InspectDatasetIdentityResponse) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *InspectDatasetIdentityResponse) GetPoolGuid() uint64 {
	if x != nil {
		return x.PoolGuid
	}
	return 0
}

type InspectStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectStateRequest) Reset() {
	*x = InspectStateRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectStateRequest) ProtoMessage() {}

func (x *InspectStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectStateRequest.ProtoReflect.Descriptor instead.
func (*InspectStateRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{7}
}

func (x *InspectStateRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *InspectStateRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Guid          uint64                 `protobuf:"varint,3,opt,name=guid,proto3" json:"guid,omitempty"`
	Creation      int64                  `protobuf:"varint,4,opt,name=creation,proto3" json:"creation,omitempty"`
	CreateTxg     uint64                 `protobuf:"varint,5,opt,name=create_txg,json=createTxg,proto3" json:"create_txg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{8}
}

func (x *Object) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Object) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Object) GetGuid() uint64 {
	if x != nil {
		return x.Guid
	}
	return 0
}

func (x *Object) GetCreation() int64 {
	if x != nil {
		return x.Creation
	}
	return 0
}

func (x *Object) GetCreateTxg() uint64 {
	if x != nil {
		return x.CreateTxg
	}
	return 0
}

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{9}
}

func (x *Property) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Property) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ReceivedProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceivedProperty) Reset() {
	*x = ReceivedProperty{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceivedProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedProperty) ProtoMessage() {}

func (x *ReceivedProperty) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedProperty.ProtoReflect.Descriptor instead.
func (*ReceivedProperty) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{10}
}

func (x *ReceivedProperty) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *ReceivedProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReceivedProperty) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NamedValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedValue) Reset() {
	*x = NamedValue{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedValue) ProtoMessage() {}

func (x *NamedValue) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedValue.ProtoReflect.Descriptor instead.
func (*NamedValue) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{11}
}

func (x *NamedValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type NamedValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedValues) Reset() {
	*x = NamedValues{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedValues) ProtoMessage() {}

func (x *NamedValues) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedValues.ProtoReflect.Descriptor instead.
func (*NamedValues) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{12}
}

func (x *NamedValues) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type InspectStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Object              `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Properties    []*Property            `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	Received      []*ReceivedProperty    `protobuf:"bytes,3,rep,name=received,proto3" json:"received,omitempty"`
	ResumeTokens  []*NamedValue          `protobuf:"bytes,4,rep,name=resume_tokens,json=resumeTokens,proto3" json:"resume_tokens,omitempty"`
	Clones        []*NamedValues         `protobuf:"bytes,5,rep,name=clones,proto3" json:"clones,omitempty"`
	Holds         []*NamedValues         `protobuf:"bytes,6,rep,name=holds,proto3" json:"holds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectStateResponse) Reset() {
	*x = InspectStateResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectStateResponse) ProtoMessage() {}

func (x *InspectStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectStateResponse.ProtoReflect.Descriptor instead.
func (*InspectStateResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{13}
}

func (x *InspectStateResponse) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *InspectStateResponse) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *InspectStateResponse) GetReceived() []*ReceivedProperty {
	if x != nil {
		return x.Received
	}
	return nil
}

func (x *InspectStateResponse) GetResumeTokens() []*NamedValue {
	if x != nil {
		return x.ResumeTokens
	}
	return nil
}

func (x *InspectStateResponse) GetClones() []*NamedValues {
	if x != nil {
		return x.Clones
	}
	return nil
}

func (x *InspectStateResponse) GetHolds() []*NamedValues {
	if x != nil {
		return x.Holds
	}
	return nil
}

type CreateReceiveParentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceiveParentRequest) Reset() {
	*x = CreateReceiveParentRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceiveParentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiveParentRequest) ProtoMessage() {}

func (x *CreateReceiveParentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiveParentRequest.ProtoReflect.Descriptor instead.
func (*CreateReceiveParentRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{14}
}

func (x *CreateReceiveParentRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

type CreateReceiveParentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReceiveParentResponse) Reset() {
	*x = CreateReceiveParentResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReceiveParentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReceiveParentResponse) ProtoMessage() {}

func (x *CreateReceiveParentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReceiveParentResponse.ProtoReflect.Descriptor instead.
func (*CreateReceiveParentResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{15}
}

type AbortReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortReceiveRequest) Reset() {
	*x = AbortReceiveRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortReceiveRequest) ProtoMessage() {}

func (x *AbortReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortReceiveRequest.ProtoReflect.Descriptor instead.
func (*AbortReceiveRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{16}
}

func (x *AbortReceiveRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

type AbortReceiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortReceiveResponse) Reset() {
	*x = AbortReceiveResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortReceiveResponse) ProtoMessage() {}

func (x *AbortReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortReceiveResponse.ProtoReflect.Descriptor instead.
func (*AbortReceiveResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{17}
}

type DestroyDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyDatasetRequest) Reset() {
	*x = DestroyDatasetRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyDatasetRequest) ProtoMessage() {}

func (x *DestroyDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyDatasetRequest.ProtoReflect.Descriptor instead.
func (*DestroyDatasetRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{18}
}

func (x *DestroyDatasetRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *DestroyDatasetRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type DestroyDatasetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyDatasetResponse) Reset() {
	*x = DestroyDatasetResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyDatasetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyDatasetResponse) ProtoMessage() {}

func (x *DestroyDatasetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyDatasetResponse.ProtoReflect.Descriptor instead.
func (*DestroyDatasetResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{19}
}

type SetPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPropertiesRequest) Reset() {
	*x = SetPropertiesRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPropertiesRequest) ProtoMessage() {}

func (x *SetPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPropertiesRequest.ProtoReflect.Descriptor instead.
func (*SetPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{20}
}

func (x *SetPropertiesRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *SetPropertiesRequest) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type InheritPropertyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Property      string                 `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InheritPropertyRequest) Reset() {
	*x = InheritPropertyRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InheritPropertyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InheritPropertyRequest) ProtoMessage() {}

func (x *InheritPropertyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InheritPropertyRequest.ProtoReflect.Descriptor instead.
func (*InheritPropertyRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{21}
}

func (x *InheritPropertyRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *InheritPropertyRequest) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

type SetPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPropertiesResponse) Reset() {
	*x = SetPropertiesResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPropertiesResponse) ProtoMessage() {}

func (x *SetPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPropertiesResponse.ProtoReflect.Descriptor instead.
func (*SetPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{22}
}

type InheritPropertyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InheritPropertyResponse) Reset() {
	*x = InheritPropertyResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InheritPropertyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InheritPropertyResponse) ProtoMessage() {}

func (x *InheritPropertyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InheritPropertyResponse.ProtoReflect.Descriptor instead.
func (*InheritPropertyResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{23}
}

type ReceiveOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          string                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Discard       string                 `protobuf:"bytes,2,opt,name=discard,proto3" json:"discard,omitempty"`
	Set           map[string]string      `protobuf:"bytes,3,rep,name=set,proto3" json:"set,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Exclude       []string               `protobuf:"bytes,4,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveOptions) Reset() {
	*x = ReceiveOptions{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveOptions) ProtoMessage() {}

func (x *ReceiveOptions) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveOptions.ProtoReflect.Descriptor instead.
func (*ReceiveOptions) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{24}
}

func (x *ReceiveOptions) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *ReceiveOptions) GetDiscard() string {
	if x != nil {
		return x.Discard
	}
	return ""
}

func (x *ReceiveOptions) GetSet() map[string]string {
	if x != nil {
		return x.Set
	}
	return nil
}

func (x *ReceiveOptions) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type ReceiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *ReceiveOptions        `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{25}
}

func (x *ReceiveRequest) GetOptions() *ReceiveOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ReceiveRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReceiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         uint64                 `protobuf:"varint,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveResponse) Reset() {
	*x = ReceiveResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveResponse) ProtoMessage() {}

func (x *ReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveResponse.ProtoReflect.Descriptor instead.
func (*ReceiveResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{26}
}

func (x *ReceiveResponse) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type CheckPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       string                 `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsRequest) Reset() {
	*x = CheckPermissionsRequest{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsRequest) ProtoMessage() {}

func (x *CheckPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{27}
}

func (x *CheckPermissionsRequest) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *CheckPermissionsRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CheckPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionsResponse) Reset() {
	*x = CheckPermissionsResponse{}
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionsResponse) ProtoMessage() {}

func (x *CheckPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_boomerangz_replication_v1_remote_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionsResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_boomerangz_replication_v1_remote_proto_rawDescGZIP(), []int{28}
}

var File_boomerangz_replication_v1_remote_proto protoreflect.FileDescriptor

const file_boomerangz_replication_v1_remote_proto_rawDesc = "" +
	"\n" +
	"&boomerangz/replication/v1/remote.proto\x12\x19boomerangz.replication.v1\"\x15\n" +
	"\x13CapabilitiesRequest\"a\n" +
	"\x14CapabilitiesResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1e\n" +
	"\n" +
	"operations\x18\x02 \x03(\tR\n" +
	"operations\"\x15\n" +
	"\x13ListDatasetsRequest\"Z\n" +
	"\aDataset\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12'\n" +
	"\x0fencryption_root\x18\x03 \x01(\tR\x0eencryptionRoot\"V\n" +
	"\x14ListDatasetsResponse\x12>\n" +
	"\bdatasets\x18\x01 \x03(\v2\".boomerangz.replication.v1.DatasetR\bdatasets\"9\n" +
	"\x1dInspectDatasetIdentityRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\"\x8d\x01\n" +
	"\x1eInspectDatasetIdentityResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04guid\x18\x03 \x01(\x04R\x04guid\x12\x12\n" +
	"\x04pool\x18\x04 \x01(\tR\x04pool\x12\x1b\n" +
	"\tpool_guid\x18\x05 \x01(\x04R\bpoolGuid\"M\n" +
	"\x13InspectStateRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\x7f\n" +
	"\x06Object\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04guid\x18\x03 \x01(\x04R\x04guid\x12\x1a\n" +
	"\bcreation\x18\x04 \x01(\x03R\bcreation\x12\x1d\n" +
	"\n" +
	"create_txg\x18\x05 \x01(\x04R\tcreateTxg\"f\n" +
	"\bProperty\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"V\n" +
	"\x10ReceivedProperty\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"6\n" +
	"\n" +
	"NamedValue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"9\n" +
	"\vNamedValues\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\xab\x03\n" +
	"\x14InspectStateResponse\x12;\n" +
	"\aobjects\x18\x01 \x03(\v2!.boomerangz.replication.v1.ObjectR\aobjects\x12C\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2#.boomerangz.replication.v1.PropertyR\n" +
	"properties\x12G\n" +
	"\breceived\x18\x03 \x03(\v2+.boomerangz.replication.v1.ReceivedPropertyR\breceived\x12J\n" +
	"\rresume_tokens\x18\x04 \x03(\v2%.boomerangz.replication.v1.NamedValueR\fresumeTokens\x12>\n" +
	"\x06clones\x18\x05 \x03(\v2&.boomerangz.replication.v1.NamedValuesR\x06clones\x12<\n" +
	"\x05holds\x18\x06 \x03(\v2&.boomerangz.replication.v1.NamedValuesR\x05holds\"6\n" +
	"\x1aCreateReceiveParentRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\"\x1d\n" +
	"\x1bCreateReceiveParentResponse\"/\n" +
	"\x13AbortReceiveRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\"\x16\n" +
	"\x14AbortReceiveResponse\"O\n" +
	"\x15DestroyDatasetRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\x18\n" +
	"\x16DestroyDatasetResponse\"\xd0\x01\n" +
	"\x14SetPropertiesRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12_\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2?.boomerangz.replication.v1.SetPropertiesRequest.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\x16InheritPropertyRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12\x1a\n" +
	"\bproperty\x18\x02 \x01(\tR\bproperty\"\x17\n" +
	"\x15SetPropertiesResponse\"\x19\n" +
	"\x17InheritPropertyResponse\"\xd6\x01\n" +
	"\x0eReceiveOptions\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12\x18\n" +
	"\adiscard\x18\x02 \x01(\tR\adiscard\x12D\n" +
	"\x03set\x18\x03 \x03(\v22.boomerangz.replication.v1.ReceiveOptions.SetEntryR\x03set\x12\x18\n" +
	"\aexclude\x18\x04 \x03(\tR\aexclude\x1a6\n" +
	"\bSetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"i\n" +
	"\x0eReceiveRequest\x12C\n" +
	"\aoptions\x18\x01 \x01(\v2).boomerangz.replication.v1.ReceiveOptionsR\aoptions\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"'\n" +
	"\x0fReceiveResponse\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\x04R\x05bytes\"U\n" +
	"\x17CheckPermissionsRequest\x12\x18\n" +
	"\adataset\x18\x01 \x01(\tR\adataset\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\"\x1a\n" +
	"\x18CheckPermissionsResponse2\xb0\n" +
	"\n" +
	"\rRemoteService\x12o\n" +
	"\fCapabilities\x12..boomerangz.replication.v1.CapabilitiesRequest\x1a/.boomerangz.replication.v1.CapabilitiesResponse\x12o\n" +
	"\fListDatasets\x12..boomerangz.replication.v1.ListDatasetsRequest\x1a/.boomerangz.replication.v1.ListDatasetsResponse\x12\x8d\x01\n" +
	"\x16InspectDatasetIdentity\x128.boomerangz.replication.v1.InspectDatasetIdentityRequest\x1a9.boomerangz.replication.v1.InspectDatasetIdentityResponse\x12o\n" +
	"\fInspectState\x12..boomerangz.replication.v1.InspectStateRequest\x1a/.boomerangz.replication.v1.InspectStateResponse\x12{\n" +
	"\x10CheckPermissions\x122.boomerangz.replication.v1.CheckPermissionsRequest\x1a3.boomerangz.replication.v1.CheckPermissionsResponse\x12\x84\x01\n" +
	"\x13CreateReceiveParent\x125.boomerangz.replication.v1.CreateReceiveParentRequest\x1a6.boomerangz.replication.v1.CreateReceiveParentResponse\x12o\n" +
	"\fAbortReceive\x12..boomerangz.replication.v1.AbortReceiveRequest\x1a/.boomerangz.replication.v1.AbortReceiveResponse\x12u\n" +
	"\x0eDestroyDataset\x120.boomerangz.replication.v1.DestroyDatasetRequest\x1a1.boomerangz.replication.v1.DestroyDatasetResponse\x12r\n" +
	"\rSetProperties\x12/.boomerangz.replication.v1.SetPropertiesRequest\x1a0.boomerangz.replication.v1.SetPropertiesResponse\x12x\n" +
	"\x0fInheritProperty\x121.boomerangz.replication.v1.InheritPropertyRequest\x1a2.boomerangz.replication.v1.InheritPropertyResponse\x12b\n" +
	"\aReceive\x12).boomerangz.replication.v1.ReceiveRequest\x1a*.boomerangz.replication.v1.ReceiveResponse(\x01B8Z6github.com/pdf/boomerangz/internal/replication/rpc;rpcb\x06proto3"

var (
	file_boomerangz_replication_v1_remote_proto_rawDescOnce sync.Once
	file_boomerangz_replication_v1_remote_proto_rawDescData []byte
)

func file_boomerangz_replication_v1_remote_proto_rawDescGZIP() []byte {
	file_boomerangz_replication_v1_remote_proto_rawDescOnce.Do(func() {
		file_boomerangz_replication_v1_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boomerangz_replication_v1_remote_proto_rawDesc), len(file_boomerangz_replication_v1_remote_proto_rawDesc)))
	})
	return file_boomerangz_replication_v1_remote_proto_rawDescData
}

var file_boomerangz_replication_v1_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_boomerangz_replication_v1_remote_proto_goTypes = []any{
	(*CapabilitiesRequest)(nil),            // 0: boomerangz.replication.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),           // 1: boomerangz.replication.v1.CapabilitiesResponse
	(*ListDatasetsRequest)(nil),            // 2: boomerangz.replication.v1.ListDatasetsRequest
	(*Dataset)(nil),                        // 3: boomerangz.replication.v1.Dataset
	(*ListDatasetsResponse)(nil),           // 4: boomerangz.replication.v1.ListDatasetsResponse
	(*InspectDatasetIdentityRequest)(nil),  // 5: boomerangz.replication.v1.InspectDatasetIdentityRequest
	(*InspectDatasetIdentityResponse)(nil), // 6: boomerangz.replication.v1.InspectDatasetIdentityResponse
	(*InspectStateRequest)(nil),            // 7: boomerangz.replication.v1.InspectStateRequest
	(*Object)(nil),                         // 8: boomerangz.replication.v1.Object
	(*Property)(nil),                       // 9: boomerangz.replication.v1.Property
	(*ReceivedProperty)(nil),               // 10: boomerangz.replication.v1.ReceivedProperty
	(*NamedValue)(nil),                     // 11: boomerangz.replication.v1.NamedValue
	(*NamedValues)(nil),                    // 12: boomerangz.replication.v1.NamedValues
	(*InspectStateResponse)(nil),           // 13: boomerangz.replication.v1.InspectStateResponse
	(*CreateReceiveParentRequest)(nil),     // 14: boomerangz.replication.v1.CreateReceiveParentRequest
	(*CreateReceiveParentResponse)(nil),    // 15: boomerangz.replication.v1.CreateReceiveParentResponse
	(*AbortReceiveRequest)(nil),            // 16: boomerangz.replication.v1.AbortReceiveRequest
	(*AbortReceiveResponse)(nil),           // 17: boomerangz.replication.v1.AbortReceiveResponse
	(*DestroyDatasetRequest)(nil),          // 18: boomerangz.replication.v1.DestroyDatasetRequest
	(*DestroyDatasetResponse)(nil),         // 19: boomerangz.replication.v1.DestroyDatasetResponse
	(*SetPropertiesRequest)(nil),           // 20: boomerangz.replication.v1.SetPropertiesRequest
	(*InheritPropertyRequest)(nil),         // 21: boomerangz.replication.v1.InheritPropertyRequest
	(*SetPropertiesResponse)(nil),          // 22: boomerangz.replication.v1.SetPropertiesResponse
	(*InheritPropertyResponse)(nil),        // 23: boomerangz.replication.v1.InheritPropertyResponse
	(*ReceiveOptions)(nil),                 // 24: boomerangz.replication.v1.ReceiveOptions
	(*ReceiveRequest)(nil),                 // 25: boomerangz.replication.v1.ReceiveRequest
	(*ReceiveResponse)(nil),                // 26: boomerangz.replication.v1.ReceiveResponse
	(*CheckPermissionsRequest)(nil),        // 27: boomerangz.replication.v1.CheckPermissionsRequest
	(*CheckPermissionsResponse)(nil),       // 28: boomerangz.replication.v1.CheckPermissionsResponse
	nil,                                    // 29: boomerangz.replication.v1.SetPropertiesRequest.PropertiesEntry
	nil,                                    // 30: boomerangz.replication.v1.ReceiveOptions.SetEntry
}
var file_boomerangz_replication_v1_remote_proto_depIdxs = []int32{
	3,  // 0: boomerangz.replication.v1.ListDatasetsResponse.datasets:type_name -> boomerangz.replication.v1.Dataset
	8,  // 1: boomerangz.replication.v1.InspectStateResponse.objects:type_name -> boomerangz.replication.v1.Object
	9,  // 2: boomerangz.replication.v1.InspectStateResponse.properties:type_name -> boomerangz.replication.v1.Property
	10, // 3: boomerangz.replication.v1.InspectStateResponse.received:type_name -> boomerangz.replication.v1.ReceivedProperty
	11, // 4: boomerangz.replication.v1.InspectStateResponse.resume_tokens:type_name -> boomerangz.replication.v1.NamedValue
	12, // 5: boomerangz.replication.v1.InspectStateResponse.clones:type_name -> boomerangz.replication.v1.NamedValues
	12, // 6: boomerangz.replication.v1.InspectStateResponse.holds:type_name -> boomerangz.replication.v1.NamedValues
	29, // 7: boomerangz.replication.v1.SetPropertiesRequest.properties:type_name -> boomerangz.replication.v1.SetPropertiesRequest.PropertiesEntry
	30, // 8: boomerangz.replication.v1.ReceiveOptions.set:type_name -> boomerangz.replication.v1.ReceiveOptions.SetEntry
	24, // 9: boomerangz.replication.v1.ReceiveRequest.options:type_name -> boomerangz.replication.v1.ReceiveOptions
	0,  // 10: boomerangz.replication.v1.RemoteService.Capabilities:input_type -> boomerangz.replication.v1.CapabilitiesRequest
	2,  // 11: boomerangz.replication.v1.RemoteService.ListDatasets:input_type -> boomerangz.replication.v1.ListDatasetsRequest
	5,  // 12: boomerangz.replication.v1.RemoteService.InspectDatasetIdentity:input_type -> boomerangz.replication.v1.InspectDatasetIdentityRequest
	7,  // 13: boomerangz.replication.v1.RemoteService.InspectState:input_type -> boomerangz.replication.v1.InspectStateRequest
	27, // 14: boomerangz.replication.v1.RemoteService.CheckPermissions:input_type -> boomerangz.replication.v1.CheckPermissionsRequest
	14, // 15: boomerangz.replication.v1.RemoteService.CreateReceiveParent:input_type -> boomerangz.replication.v1.CreateReceiveParentRequest
	16, // 16: boomerangz.replication.v1.RemoteService.AbortReceive:input_type -> boomerangz.replication.v1.AbortReceiveRequest
	18, // 17: boomerangz.replication.v1.RemoteService.DestroyDataset:input_type -> boomerangz.replication.v1.DestroyDatasetRequest
	20, // 18: boomerangz.replication.v1.RemoteService.SetProperties:input_type -> boomerangz.replication.v1.SetPropertiesRequest
	21, // 19: boomerangz.replication.v1.RemoteService.InheritProperty:input_type -> boomerangz.replication.v1.InheritPropertyRequest
	25, // 20: boomerangz.replication.v1.RemoteService.Receive:input_type -> boomerangz.replication.v1.ReceiveRequest
	1,  // 21: boomerangz.replication.v1.RemoteService.Capabilities:output_type -> boomerangz.replication.v1.CapabilitiesResponse
	4,  // 22: boomerangz.replication.v1.RemoteService.ListDatasets:output_type -> boomerangz.replication.v1.ListDatasetsResponse
	6,  // 23: boomerangz.replication.v1.RemoteService.InspectDatasetIdentity:output_type -> boomerangz.replication.v1.InspectDatasetIdentityResponse
	13, // 24: boomerangz.replication.v1.RemoteService.InspectState:output_type -> boomerangz.replication.v1.InspectStateResponse
	28, // 25: boomerangz.replication.v1.RemoteService.CheckPermissions:output_type -> boomerangz.replication.v1.CheckPermissionsResponse
	15, // 26: boomerangz.replication.v1.RemoteService.CreateReceiveParent:output_type -> boomerangz.replication.v1.CreateReceiveParentResponse
	17, // 27: boomerangz.replication.v1.RemoteService.AbortReceive:output_type -> boomerangz.replication.v1.AbortReceiveResponse
	19, // 28: boomerangz.replication.v1.RemoteService.DestroyDataset:output_type -> boomerangz.replication.v1.DestroyDatasetResponse
	22, // 29: boomerangz.replication.v1.RemoteService.SetProperties:output_type -> boomerangz.replication.v1.SetPropertiesResponse
	23, // 30: boomerangz.replication.v1.RemoteService.InheritProperty:output_type -> boomerangz.replication.v1.InheritPropertyResponse
	26, // 31: boomerangz.replication.v1.RemoteService.Receive:output_type -> boomerangz.replication.v1.ReceiveResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_boomerangz_replication_v1_remote_proto_init() }
func file_boomerangz_replication_v1_remote_proto_init() {
	if File_boomerangz_replication_v1_remote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boomerangz_replication_v1_remote_proto_rawDesc), len(file_boomerangz_replication_v1_remote_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boomerangz_replication_v1_remote_proto_goTypes,
		DependencyIndexes: file_boomerangz_replication_v1_remote_proto_depIdxs,
		MessageInfos:      file_boomerangz_replication_v1_remote_proto_msgTypes,
	}.Build()
	File_boomerangz_replication_v1_remote_proto = out.File
	file_boomerangz_replication_v1_remote_proto_goTypes = nil
	file_boomerangz_replication_v1_remote_proto_depIdxs = nil
}
